apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 826445948167.dkr.ecr.ap-south-1.amazonaws.com/msh/portfolio:40b67c0ecd71285d4887800411aa3489dc0ef9b3
        ports:
        - containerPort: 3000
