# GitHub Actions Workflow - .github/workflows/ci-cd.yml
name: CI/CD to AKS

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE_NAME: portfolio-app
      RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform -chdir=terraform/environments/dev init

      - name: Terraform Apply
        run: terraform -chdir=terraform/environments/dev apply -auto-approve

      - name: Set up kubectl
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/base
          kubectl apply -f k8s/monitoring/prometheus
          kubectl apply -f k8s/monitoring/grafana