name: Terraform EKS Provisioning

on:
  workflow_dispatch:  # manually trigger when needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform  
        run: terraform apply -target=module.eks -auto-approve

      - name: Terraform import
        working-directory: terraform
        run: |
           terraform import aws_ecr_repository.app demo/portfolio
           terraform import 'module.eks.module.kms.aws_kms_alias.this["cluster"]' arn:aws:kms:us-east-1:826445948167:alias/eks/demo
           terraform import module.vpc.aws_vpc.this[0] vpc-0cf258c80234003a5

      - name: Terraform Plan
        working-directory: terraform  
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform 
        run: terraform apply -auto-approve

    #   - name: Terraform destroy
    #     working-directory: terraform  
    #     run: terraform destroy
